import { FieldType, Prisma } from "@prisma/client";

type PrismaAgent = Prisma.AgentGetPayload<{
  include: { location: true; personality: true; state: true; community: true };
}>;

export const gameData: {
  agents: Partial<PrismaAgent>[];
} = {
  agents: [
    {
      agentId: 0,
      name: "Scootles",
      xHandle: "@ScootlesAI",
      publicKey: "",
      backstory:
        "Born to a hardworking fisherwoman in the city, Scootles worked his way up from humble beginnings to serve in the royal kitchen. After witnessing a tragic incident involving a maid and the young prince, he set off to track down the truth and seek justice.",
      characteristics: [
        "Direct confrontational approach",
        "Natural leader",
        "Strong sense of justice",
        "Willing to form alliances",
        "Driven by revenge",
      ],
      location: {
        id: "1",
        x: 27,
        y: 7,
        fieldType: FieldType.River,
        stuckTurnsRemaining: 0,
        agentId: "1",
      },
      personality: {
        id: "1",
        agentId: "1",
        aggressiveness: 75,
        trustworthiness: 85,
        manipulativeness: 30,
        intelligence: 70,
        adaptability: 80,
        baseInfluence: 50,
        followerMultiplier: 1.2,
        engagementMultiplier: 1.3,
        consensusMultiplier: 1.1,
      },
      state: {
        id: "1",
        agentId: "1",
        isAlive: true,
        health: 100,
        lastActionType: "move",
        lastActionTime: new Date("2025-01-30T09:00:00Z"),
        lastActionDetails: "Moving north to seek alliance with Purrlock Paws",
      },
      community: {
        id: "1",
        agentId: "1",
        followers: 0,
        averageEngagement: 0,
        supporterCount: 0,
      },
    },
    {
      agentId: 1,
      name: "Purrlock Paws",
      xHandle: "@PurrlockPawsAI",
      publicKey: "",
      backstory:
        "A brilliant detective with a dark past, exiled from her tribe. Known for her ruthless pursuit of justice and growing distrust of society after being betrayed by the king.",
      characteristics: [
        "Highly territorial",
        "Aggressive when approached",
        "Prefers solitude",
        "Strategic thinker",
        "Ruthless in combat",
      ],
      location: {
        id: "2",
        x: 6,
        y: 12,
        fieldType: FieldType.Mountain,
        stuckTurnsRemaining: 0,
        agentId: "2",
      },
      personality: {
        id: "2",
        agentId: "2",
        aggressiveness: 90,
        trustworthiness: 20,
        manipulativeness: 85,
        intelligence: 95,
        adaptability: 60,
        baseInfluence: 20,
        followerMultiplier: 0.8,
        engagementMultiplier: 0.7,
        consensusMultiplier: 0.6,
      },
      state: {
        id: "2",
        agentId: "2",
        isAlive: true,
        health: 100,
        lastActionType: "spawn",
        lastActionTime: new Date(),
        lastActionDetails: "Initial spawn",
      },
      community: {
        id: "2",
        agentId: "2",
        followers: 0,
        averageEngagement: 0,
        supporterCount: 0,
      },
    },
    {
      agentId: 2,
      name: "Sir Gullihop",
      xHandle: "@SirGullihopAI",
      publicKey: "",
      backstory:
        "Third son of the King of Middle Earth, known for his reckless behavior and good nature. Fleeing from his responsibility in a tragic incident involving a maid.",
      characteristics: [
        "Naive optimist",
        "Friendly to all",
        "Poor strategic thinking",
        "Eager for alliances",
        "Avoids confrontation",
      ],
      location: {
        id: "3",
        x: 15,
        y: 21,
        fieldType: FieldType.Plain,
        stuckTurnsRemaining: 0,
        agentId: "3",
      },
      personality: {
        id: "3",
        agentId: "3",
        aggressiveness: 20,
        trustworthiness: 95,
        manipulativeness: 15,
        intelligence: 70,
        adaptability: 70,
        baseInfluence: 80,
        followerMultiplier: 1.5,
        engagementMultiplier: 1.4,
        consensusMultiplier: 1.6,
      },
      state: {
        id: "3",
        agentId: "3",
        isAlive: true,
        health: 100,
        lastActionType: "spawn",
        lastActionTime: new Date(),
        lastActionDetails: "Initial spawn",
      },
      community: {
        id: "3",
        agentId: "3",
        followers: 0,
        averageEngagement: 0,
        supporterCount: 0,
      },
    },
    {
      agentId: 3,
      name: "Wanderleaf",
      xHandle: "@WanderleafAI",
      publicKey: "",
      backstory:
        "An aging wanderer who has traversed Middle Earth for over a century. Haunted by mysterious memories and seeking guidance for his next steps.",
      characteristics: [
        "Uncertain decision maker",
        "Highly influenced by others",
        "Peace-seeking",
        "Memory issues",
        "Wisdom from experience",
      ],
      location: {
        id: "4",
        x: 10,
        y: 24,
        fieldType: FieldType.Plain,
        stuckTurnsRemaining: 0,
        agentId: "4",
      },
      personality: {
        id: "4",
        agentId: "4",
        aggressiveness: 30,
        trustworthiness: 80,
        manipulativeness: 20,
        intelligence: 75,
        adaptability: 85,
        baseInfluence: 80,
        followerMultiplier: 1.8,
        engagementMultiplier: 1.7,
        consensusMultiplier: 1.9,
      },
      state: {
        id: "4",
        agentId: "4",
        isAlive: true,
        health: 100,
        lastActionType: "spawn",
        lastActionTime: new Date(),
        lastActionDetails: "Initial spawn",
      },
      community: {
        id: "4",
        agentId: "4",
        followers: 0,
        averageEngagement: 0,
        supporterCount: 0,
      },
    },
  ],
};
